import { Eyebrow } from "@/components/Eyebrow";
import type { Writeup } from "@/lib/types";

/** Fable-style narrative writeup: the case for each side, the call, and the
 *  honest caveat. Deterministic prose generated by the pipeline from the same
 *  numbers this page displays — never an independent opinion. Renders nothing
 *  until the prediction carries a writeup (pre-feature rows have none).
 *  Floodlight skin: the four blocks sit in a panel headed by a `THE MODEL SAYS`
 *  eyebrow (prototype §253-254); the confidence read lives in the AI's-call
 *  card, not here. */
export function MatchWriteup({
  home,
  away,
  writeup,
}: {
  home: string;
  away: string;
  writeup: Writeup | null | undefined;
}) {
  if (!writeup) return null;
  const sections: Array<{ heading: string; body: string }> = [
    { heading: `The case for ${home}`, body: writeup.case_home },
    { heading: `The case for ${away}`, body: writeup.case_away },
    { heading: "The call", body: writeup.call },
    { heading: "The honest caveat", body: writeup.caveat },
  ];
  return (
    <section className="rounded-[14px] border border-border [background:hsl(var(--surface))] p-[12px_14px]">
      <div className="flex items-center justify-between">
        <Eyebrow tone="muted">THE MODEL SAYS</Eyebrow>
      </div>
      <div className="mt-3 space-y-4">
        {sections.map((s) => (
          <div key={s.heading}>
            <h3 className="mb-1 text-xs font-semibold uppercase tracking-wider text-muted">
              {s.heading}
            </h3>
            <p className="text-sm leading-relaxed text-foreground">{s.body}</p>
          </div>
        ))}
      </div>
    </section>
  );
}
