import type { Writeup } from "@/lib/types";

/** Fable-style narrative writeup: the case for each side, the call, and the
 *  honest caveat. Deterministic prose generated by the pipeline from the same
 *  numbers this page displays — never an independent opinion. Renders nothing
 *  until the prediction carries a writeup (pre-feature rows have none). */
export function MatchWriteup({
  home,
  away,
  writeup,
}: {
  home: string;
  away: string;
  writeup: Writeup | null | undefined;
}) {
  if (!writeup) return null;
  const sections: Array<{ heading: string; body: string }> = [
    { heading: `The case for ${home}`, body: writeup.case_home },
    { heading: `The case for ${away}`, body: writeup.case_away },
    { heading: "The call", body: writeup.call },
    { heading: "The honest caveat", body: writeup.caveat },
  ];
  return (
    <section className="glass rounded-2xl p-6">
      <h2 className="mb-4 font-display text-lg font-bold text-foreground">The breakdown</h2>
      <div className="space-y-4">
        {sections.map((s) => (
          <div key={s.heading}>
            <h3 className="mb-1 text-xs font-semibold uppercase tracking-wider text-muted">
              {s.heading}
            </h3>
            <p className="text-sm leading-relaxed text-foreground">{s.body}</p>
          </div>
        ))}
      </div>
    </section>
  );
}
