"""Fit the in-play win-probability logistic from historical NRL results
(Wave 3). See ml/sports/nrl/live_model.py's module docstring: NRL ingest
has no half-time/minute data, so training rows are generated by simulating
scoring-event timings anchored to each match's real final score and real
eventual winner.

CLI: python -m pipeline.sports.nrl_live_fit --seed 42 --trajectories-per-match 20
"""
from __future__ import annotations

import argparse
import logging

import numpy as np
from sqlalchemy.orm import Session

from app.models import SportMatch, SportPrediction
from ml.sports.nrl.live_model import LiveWinProbModel
from ml.sports.nrl.live_params import NrlLiveParams, save_nrl_live_params

log = logging.getLogger(__name__)

MATCH_MINUTES = 80.0
# Rough NRL scoring-play split (penalty goal / unconverted try / converted
# try) used only to make simulated event VALUES plausible -- the timing is
# synthetic regardless, so this doesn't need to be precise.
POINT_VALUES = [2, 4, 6]
POINT_WEIGHTS = [0.20, 0.15, 0.65]
CHECKPOINTS_PER_TRAJECTORY = 5
MIN_MATCHES_TO_FIT = 20


def simulate_score_trajectory(final_score: int, rng: np.random.Generator) -> list[tuple[float, int]]:
    """Return [(minute, cumulative_score), ...], strictly increasing in
    minute, summing exactly to final_score. The TIMING is synthetic
    (independently uniform-random in [0, 80)); the total is real."""
    events: list[tuple[float, int]] = []
    remaining = final_score
    while remaining > 0:
        choices = [v for v in POINT_VALUES if v <= remaining] or [remaining]
        weights = np.array([
            POINT_WEIGHTS[POINT_VALUES.index(v)] if v in POINT_VALUES else 1.0
            for v in choices
        ])
        value = int(rng.choice(choices, p=weights / weights.sum()))
        minute = float(rng.uniform(0, MATCH_MINUTES))
        events.append((minute, value))
        remaining -= value
    events.sort(key=lambda e: e[0])
    cum = 0
    out = []
    for minute, value in events:
        cum += value
        out.append((minute, cum))
    return out


def _score_at(trajectory: list[tuple[float, int]], minute: float) -> int:
    score = 0
    for t, cum in trajectory:
        if t <= minute:
            score = cum
        else:
            break
    return score


def generate_training_rows(
    matches: list[dict],
    trajectories_per_match: int = 20,
    checkpoints_per_trajectory: int = CHECKPOINTS_PER_TRAJECTORY,
    seed: int = 42,
) -> list[dict]:
    """matches: [{"score_home", "score_away", "pregame_prob"}, ...]. Returns
    rows with keys score_diff/minutes_remaining/pregame_prob/home_won."""
    rng = np.random.default_rng(seed)
    rows: list[dict] = []
    for m in matches:
        home_won = m["score_home"] > m["score_away"]
        for _ in range(trajectories_per_match):
            home_traj = simulate_score_trajectory(m["score_home"], rng)
            away_traj = simulate_score_trajectory(m["score_away"], rng)
            checkpoints = sorted(rng.uniform(0, MATCH_MINUTES, size=checkpoints_per_trajectory))
            for minute in checkpoints:
                sh = _score_at(home_traj, minute)
                sa = _score_at(away_traj, minute)
                rows.append({
                    "score_diff": float(sh - sa),
                    "minutes_remaining": MATCH_MINUTES - float(minute),
                    "pregame_prob": m["pregame_prob"],
                    "home_won": home_won,
                })
    return rows


def _finished_matches_with_pregame_prob(db: Session) -> list[dict]:
    """Finished nrl matches paired with their latest PRE-KICKOFF prediction
    -- same eligibility rule as pipeline.sports.nrl_predict.grade(), so the
    fitting set matches exactly what the live poller reads at runtime."""
    out = []
    finished = db.query(SportMatch).filter_by(sport="nrl", status="finished").all()
    for m in finished:
        if m.score_home is None or m.score_away is None:
            continue
        q = db.query(SportPrediction).filter_by(match_id=m.id)
        if m.kickoff_utc is not None:
            q = q.filter(SportPrediction.created_at <= m.kickoff_utc)
        latest = q.order_by(SportPrediction.created_at.desc(), SportPrediction.id.desc()).first()
        if latest is None:
            continue
        out.append({"score_home": m.score_home, "score_away": m.score_away, "pregame_prob": latest.p_home})
    return out


def fit_from_db(
    db: Session, trajectories_per_match: int = 20, seed: int = 42, version: str = "nrl-live-v0.1",
) -> NrlLiveParams:
    matches = _finished_matches_with_pregame_prob(db)
    if len(matches) < MIN_MATCHES_TO_FIT:
        log.warning("only %d finished+predicted nrl matches -- keeping default live params", len(matches))
        return NrlLiveParams()
    rows = generate_training_rows(matches, trajectories_per_match=trajectories_per_match, seed=seed)
    try:
        fitted = LiveWinProbModel().fit(rows)
        return NrlLiveParams(version=version, **fitted.coefficients())
    except Exception as e:
        log.warning("failed to fit live model: %s -- keeping default coefficients", e)
        return NrlLiveParams(version=version)


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--trajectories-per-match", type=int, default=20)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--version", default="nrl-live-v0.1")
    args = ap.parse_args()

    from app.db import SessionLocal

    db = SessionLocal()
    try:
        params = fit_from_db(db, trajectories_per_match=args.trajectories_per_match,
                              seed=args.seed, version=args.version)
        save_nrl_live_params(params)
        log.info("nrl live-model fit: %s", params)
    finally:
        db.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
