"""initial MVP schema

Revision ID: cc991b98094e
Revises: 
Create Date: 2026-06-06 16:24:44.631866
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cc991b98094e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('confederation', sa.String(length=20), nullable=True),
    sa.Column('fifa_rank', sa.Integer(), nullable=True),
    sa.Column('elo_rating', sa.Float(), nullable=True),
    sa.Column('flag_url', sa.String(length=300), nullable=True),
    sa.Column('is_host', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=True)

    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('host_countries', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_b_id', sa.Integer(), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=False),
    sa.Column('score_b', sa.Integer(), nullable=False),
    sa.Column('competition', sa.String(length=80), nullable=True),
    sa.Column('is_neutral', sa.Boolean(), nullable=False),
    sa.Column('venue', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'team_a_id', 'team_b_id', name='uq_historical_match')
    )
    with op.batch_alter_table('historical_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_matches_date'), ['date'], unique=False)

    op.create_table('team_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=False),
    sa.Column('form_points_last10', sa.Float(), nullable=True),
    sa.Column('xg_for', sa.Float(), nullable=True),
    sa.Column('xg_against', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'team_id', name='uq_group_team')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('team_home_id', sa.Integer(), nullable=True),
    sa.Column('team_away_id', sa.Integer(), nullable=True),
    sa.Column('kickoff_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue', sa.String(length=120), nullable=True),
    sa.Column('venue_country', sa.String(length=40), nullable=True),
    sa.Column('is_neutral', sa.Boolean(), nullable=False),
    sa.Column('host_team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score_home', sa.Integer(), nullable=True),
    sa.Column('score_away', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['host_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_away_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_home_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_diff', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('qualification_prob', sa.Float(), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('bookmaker', sa.String(length=60), nullable=True),
    sa.Column('odds_home', sa.Float(), nullable=True),
    sa.Column('odds_draw', sa.Float(), nullable=True),
    sa.Column('odds_away', sa.Float(), nullable=True),
    sa.Column('implied_prob_home', sa.Float(), nullable=True),
    sa.Column('implied_prob_draw', sa.Float(), nullable=True),
    sa.Column('implied_prob_away', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prob_home_win', sa.Float(), nullable=False),
    sa.Column('prob_draw', sa.Float(), nullable=False),
    sa.Column('prob_away_win', sa.Float(), nullable=False),
    sa.Column('predicted_score_home', sa.Integer(), nullable=True),
    sa.Column('predicted_score_away', sa.Integer(), nullable=True),
    sa.Column('predicted_score_prob', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('top_features', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_match_id'), ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_match_id'))

    op.drop_table('predictions')
    op.drop_table('odds')
    op.drop_table('standings')
    op.drop_table('matches')
    op.drop_table('group_teams')
    op.drop_table('team_stats')
    with op.batch_alter_table('historical_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_matches_date'))

    op.drop_table('historical_matches')
    op.drop_table('groups')
    op.drop_table('tournaments')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_name'))

    op.drop_table('teams')
    # ### end Alembic commands ###
